# Generated by Django 4.2.20 on 2025-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='code snippet'),
        ),
    ]
