# Generated by Django 4.2.20 on 2025-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('project_invite', 'Project Invitation'), ('project_request', 'Project Request'), ('project_accepted', 'Project Request Accepted')], max_length=20, verbose_name='type')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_likes', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('email_follows', models.BooleanField(default=True)),
                ('email_mentions', models.BooleanField(default=True)),
                ('email_project_invites', models.BooleanField(default=True)),
                ('email_project_requests', models.BooleanField(default=True)),
                ('push_likes', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=True)),
                ('push_follows', models.BooleanField(default=True)),
                ('push_mentions', models.BooleanField(default=True)),
                ('push_project_invites', models.BooleanField(default=True)),
                ('push_project_requests', models.BooleanField(default=True)),
            ],
        ),
    ]
